#!/usr/bin/env node
/**
 * Scans content/ for all media extensions and writes src/data/media-manifest.ts.
 * Prefers optimized files under public/media when present.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const AUDIO_EXT = new Set([
  '.mp3',
  '.wav',
  '.flac',
  '.m4a',
  '.aac',
  '.ogg',
  '.aiff',
  '.aif',
  '.wma',
])
const IMAGE_EXT = new Set([
  '.jpg',
  '.jpeg',
  '.png',
  '.webp',
  '.gif',
  '.avif',
  '.bmp',
  '.tif',
  '.tiff',
])

/** @type {Record<string, { kind: string, publicSub: string }>} */
const FOLDERS = {
  tracks: { kind: 'track', publicSub: 'tracks' },
  sets: { kind: 'set', publicSub: 'sets' },
  fotos: { kind: 'photo', publicSub: 'fotos' },
  'profile-image': { kind: 'profile', publicSub: 'profile' },
  'background-images': { kind: 'background', publicSub: 'backgrounds' },
}

function titleFromFilename(filename) {
  return filename
    .replace(/\.[^.]+$/, '')
    .replace(/[_]+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim()
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function listFiles(dir) {
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isFile() && !d.name.startsWith('.'))
    .map((d) => d.name)
}

function isMedia(ext, kind) {
  if (kind === 'track' || kind === 'set') return AUDIO_EXT.has(ext)
  return IMAGE_EXT.has(ext)
}

function findOptimized(publicSub, baseSlug, preferredExts) {
  const dir = path.join(root, 'public', 'media', publicSub)
  if (!fs.existsSync(dir)) return null
  const files = listFiles(dir)
  for (const ext of preferredExts) {
    const match = files.find(
      (f) =>
        path.parse(f).name === baseSlug ||
        slugify(path.parse(f).name) === baseSlug,
    )
    if (match && path.extname(match).toLowerCase() === ext) {
      return `/media/${publicSub}/${match}`
    }
  }
  // Any optimized sibling with same slug
  const any = files.find((f) => slugify(path.parse(f).name) === baseSlug)
  return any ? `/media/${publicSub}/${any}` : null
}

function webPreferred(kind, originalExt) {
  if (kind === 'track' || kind === 'set') {
    if (originalExt === '.mp3') return ['.mp3']
    return ['.mp3', originalExt]
  }
  return ['.jpg', '.jpeg', '.webp', '.png', originalExt]
}

function scan() {
  /** @type {Record<string, object[]>} */
  const buckets = {
    tracks: [],
    sets: [],
    photos: [],
    profile: [],
    backgrounds: [],
  }

  const bucketKey = {
    track: 'tracks',
    set: 'sets',
    photo: 'photos',
    profile: 'profile',
    background: 'backgrounds',
  }

  for (const [folder, meta] of Object.entries(FOLDERS)) {
    const dir = path.join(root, 'content', folder)
    for (const filename of listFiles(dir)) {
      const ext = path.extname(filename).toLowerCase()
      if (!isMedia(ext, meta.kind)) continue

      const originalPath = path.join('content', folder, filename)
      const abs = path.join(root, originalPath)
      const stat = fs.statSync(abs)
      const baseSlug = slugify(path.parse(filename).name)
      const preferred = webPreferred(meta.kind, ext)
      const optimized = findOptimized(meta.publicSub, baseSlug, preferred)

      // Fallback: serve original via Vite public symlink path we copy on optimize;
      // until optimized, point to a content bridge URL under /media raw copy if exists,
      // else use optimize output path expectation.
      let src = optimized
      if (!src) {
        // Place a stable public URL that optimize-media will populate
        const outExt =
          meta.kind === 'track' || meta.kind === 'set' ? '.mp3' : '.jpg'
        src = `/media/${meta.publicSub}/${baseSlug}${outExt}`
      }

      const item = {
        id: `${meta.kind}-${baseSlug}`,
        kind: meta.kind,
        title: titleFromFilename(filename),
        filename,
        format: ext.replace('.', ''),
        src,
        originalPath: originalPath.replace(/\\/g, '/'),
        bytes: stat.size,
      }

      buckets[bucketKey[meta.kind]].push(item)
    }
  }

  for (const key of Object.keys(buckets)) {
    buckets[key].sort((a, b) => a.title.localeCompare(b.title, 'pt-BR'))
  }

  return {
    generatedAt: new Date().toISOString(),
    ...buckets,
  }
}

function writeManifest(manifest) {
  const outDir = path.join(root, 'src', 'data')
  fs.mkdirSync(outDir, { recursive: true })
  const outFile = path.join(outDir, 'media-manifest.ts')
  const json = JSON.stringify(manifest, null, 2)
  const body = `/* Auto-generated by scripts/scan-media.mjs — do not edit */
import type { MediaManifest } from '@/lib/media'

export const mediaManifest: MediaManifest = ${json}
`
  fs.writeFileSync(outFile, body, 'utf8')
  console.log(
    `Wrote ${outFile} — tracks:${manifest.tracks.length} sets:${manifest.sets.length} photos:${manifest.photos.length}`,
  )
}

writeManifest(scan())
