#!/usr/bin/env node
/**
 * Scans public/media for web assets and writes src/data/media-manifest.ts.
 * Audio is expected as .mp3; images as common web formats.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const AUDIO_EXT = new Set(['.mp3', '.m4a', '.aac', '.ogg'])
const IMAGE_EXT = new Set([
  '.jpg',
  '.jpeg',
  '.png',
  '.webp',
  '.gif',
  '.avif',
])

/** @type {Record<string, { kind: string, bucket: string }>} */
const FOLDERS = {
  tracks: { kind: 'track', bucket: 'tracks' },
  sets: { kind: 'set', bucket: 'sets' },
  fotos: { kind: 'photo', bucket: 'photos' },
  profile: { kind: 'profile', bucket: 'profile' },
  backgrounds: { kind: 'background', bucket: 'backgrounds' },
}

function titleFromFilename(filename) {
  return filename
    .replace(/\.[^.]+$/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim()
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function listFiles(dir) {
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isFile() && !d.name.startsWith('.'))
    .map((d) => d.name)
}

function isMedia(ext, kind) {
  if (kind === 'track' || kind === 'set') return AUDIO_EXT.has(ext)
  return IMAGE_EXT.has(ext)
}

function scan() {
  /** @type {Record<string, object[]>} */
  const buckets = {
    tracks: [],
    sets: [],
    photos: [],
    profile: [],
    backgrounds: [],
  }

  for (const [folder, meta] of Object.entries(FOLDERS)) {
    const dir = path.join(root, 'public', 'media', folder)
    for (const filename of listFiles(dir)) {
      const ext = path.extname(filename).toLowerCase()
      if (!isMedia(ext, meta.kind)) continue

      const abs = path.join(dir, filename)
      const stat = fs.statSync(abs)
      const baseSlug = slugify(path.parse(filename).name)
      const format = ext.replace('.', '')
      const waveformPath = path.join(
        root,
        'public',
        'media',
        'waveforms',
        `${baseSlug}.json`,
      )
      const waveformSrc = fs.existsSync(waveformPath)
        ? `/media/waveforms/${baseSlug}.json`
        : undefined

      /** @type {Record<string, unknown>} */
      const item = {
        id: `${meta.kind}-${baseSlug}`,
        kind: meta.kind,
        title: titleFromFilename(filename),
        filename,
        format,
        src: `/media/${folder}/${filename}`,
        originalPath: `public/media/${folder}/${filename}`,
        bytes: stat.size,
      }
      if (waveformSrc) item.waveformSrc = waveformSrc

      buckets[meta.bucket].push(item)
    }
  }

  for (const key of Object.keys(buckets)) {
    buckets[key].sort((a, b) => a.title.localeCompare(b.title, 'pt-BR'))
  }

  return {
    generatedAt: new Date().toISOString(),
    ...buckets,
  }
}

function writeManifest(manifest) {
  const outDir = path.join(root, 'src', 'data')
  fs.mkdirSync(outDir, { recursive: true })
  const outFile = path.join(outDir, 'media-manifest.ts')
  const json = JSON.stringify(manifest, null, 2)
  const body = `/* Auto-generated by scripts/scan-media.mjs — do not edit */
import type { MediaManifest } from '@/lib/media'

export const mediaManifest: MediaManifest = ${json}
`
  fs.writeFileSync(outFile, body, 'utf8')
  console.log(
    `Wrote ${outFile} — tracks:${manifest.tracks.length} sets:${manifest.sets.length} photos:${manifest.photos.length}`,
  )
}

writeManifest(scan())
