/* Auto-generated by scripts/scan-media.mjs — do not edit */
import type { MediaManifest } from '@/lib/media'

export const mediaManifest: MediaManifest = {
  "generatedAt": "2026-08-07T00:32:23.981Z",
  "tracks": [
    {
      "id": "track-house-base",
      "kind": "track",
      "title": "House - base",
      "filename": "House - base.flac",
      "format": "flac",
      "src": "/media/tracks/house-base.mp3",
      "originalPath": "content/tracks/House - base.flac",
      "bytes": 19289537
    },
    {
      "id": "track-illuminated-path",
      "kind": "track",
      "title": "Illuminated Path",
      "filename": "Illuminated_Path.wav",
      "format": "wav",
      "src": "/media/tracks/illuminated-path.mp3",
      "originalPath": "content/tracks/Illuminated_Path.wav",
      "bytes": 31753496
    },
    {
      "id": "track-kfx",
      "kind": "track",
      "title": "KFX",
      "filename": "KFX.flac",
      "format": "flac",
      "src": "/media/tracks/kfx.mp3",
      "originalPath": "content/tracks/KFX.flac",
      "bytes": 54966951
    },
    {
      "id": "track-piano",
      "kind": "track",
      "title": "Piano",
      "filename": "Piano.flac",
      "format": "flac",
      "src": "/media/tracks/piano.mp3",
      "originalPath": "content/tracks/Piano.flac",
      "bytes": 51951336
    },
    {
      "id": "track-soulful-dreams",
      "kind": "track",
      "title": "Soulful Dreams",
      "filename": "Soulful_Dreams.wav",
      "format": "wav",
      "src": "/media/tracks/soulful-dreams.mp3",
      "originalPath": "content/tracks/Soulful_Dreams.wav",
      "bytes": 44966744
    }
  ],
  "sets": [
    {
      "id": "set-thur-mershup-techno-x-prog-house",
      "kind": "set",
      "title": "Thur - Mershup Techno x Prog House",
      "filename": "Thur - Mershup Techno x Prog House.mp3",
      "format": "mp3",
      "src": "/media/sets/thur-mershup-techno-x-prog-house.mp3",
      "originalPath": "content/sets/Thur - Mershup Techno x Prog House.mp3",
      "bytes": 30154009
    },
    {
      "id": "set-thur-mix-rec-2022-02-19",
      "kind": "set",
      "title": "Thur - Mix REC-2022-02-19",
      "filename": "Thur - Mix REC-2022-02-19.wav",
      "format": "wav",
      "src": "/media/sets/thur-mix-rec-2022-02-19.mp3",
      "originalPath": "content/sets/Thur - Mix REC-2022-02-19.wav",
      "bytes": 483638016
    },
    {
      "id": "set-thur-tech-house-music-mix01012022",
      "kind": "set",
      "title": "Thur - Tech House Music mix01012022",
      "filename": "Thur - Tech House Music mix01012022.mp3",
      "format": "mp3",
      "src": "/media/sets/thur-tech-house-music-mix01012022.mp3",
      "originalPath": "content/sets/Thur - Tech House Music mix01012022.mp3",
      "bytes": 29237390
    },
    {
      "id": "set-thur2guima-progressive-sunrise-19-03-22",
      "kind": "set",
      "title": "Thur2Guima - Progressive Sunrise 19-03-22",
      "filename": "Thur2Guima - Progressive Sunrise 19-03-22.wav",
      "format": "wav",
      "src": "/media/sets/thur2guima-progressive-sunrise-19-03-22.mp3",
      "originalPath": "content/sets/Thur2Guima - Progressive Sunrise 19-03-22.wav",
      "bytes": 724817662
    },
    {
      "id": "set-thur2luca-house-music-sunset",
      "kind": "set",
      "title": "Thur2Luca - House Music Sunset",
      "filename": "Thur2Luca  - House Music Sunset.mp3",
      "format": "mp3",
      "src": "/media/sets/thur2luca-house-music-sunset.mp3",
      "originalPath": "content/sets/Thur2Luca  - House Music Sunset.mp3",
      "bytes": 79704503
    }
  ],
  "photos": [
    {
      "id": "photo-boat-img-jul-2023-1",
      "kind": "photo",
      "title": "BOAT IMG JUL 2023 1",
      "filename": "BOAT_IMG_JUL_2023_1.jpg",
      "format": "jpg",
      "src": "/media/fotos/boat-img-jul-2023-1.jpg",
      "originalPath": "content/fotos/BOAT_IMG_JUL_2023_1.jpg",
      "bytes": 291738
    },
    {
      "id": "photo-boat-img-jul-2023-2",
      "kind": "photo",
      "title": "BOAT IMG JUL 2023 2",
      "filename": "BOAT_IMG_JUL_2023_2.jpg",
      "format": "jpg",
      "src": "/media/fotos/boat-img-jul-2023-2.jpg",
      "originalPath": "content/fotos/BOAT_IMG_JUL_2023_2.jpg",
      "bytes": 281123
    },
    {
      "id": "photo-boat-img-jul-2023-3",
      "kind": "photo",
      "title": "BOAT IMG JUL 2023 3",
      "filename": "BOAT_IMG_JUL_2023_3.jpg",
      "format": "jpg",
      "src": "/media/fotos/boat-img-jul-2023-3.jpg",
      "originalPath": "content/fotos/BOAT_IMG_JUL_2023_3.jpg",
      "bytes": 133513
    },
    {
      "id": "photo-img-hand",
      "kind": "photo",
      "title": "IMG hand",
      "filename": "IMG_hand.jpg",
      "format": "jpg",
      "src": "/media/fotos/img-hand.jpg",
      "originalPath": "content/fotos/IMG_hand.jpg",
      "bytes": 122335
    },
    {
      "id": "photo-img-thur",
      "kind": "photo",
      "title": "IMG Thur",
      "filename": "IMG_Thur.png",
      "format": "png",
      "src": "/media/fotos/img-thur.jpg",
      "originalPath": "content/fotos/IMG_Thur.png",
      "bytes": 33008485
    },
    {
      "id": "photo-img-thur-reserva",
      "kind": "photo",
      "title": "IMG Thur reserva",
      "filename": "IMG_Thur_reserva.JPG",
      "format": "jpg",
      "src": "/media/fotos/img-thur-reserva.jpg",
      "originalPath": "content/fotos/IMG_Thur_reserva.JPG",
      "bytes": 3870216
    }
  ],
  "profile": [
    {
      "id": "profile-img-thur-reserva",
      "kind": "profile",
      "title": "IMG Thur reserva",
      "filename": "IMG_Thur_reserva.JPG",
      "format": "jpg",
      "src": "/media/profile/img-thur-reserva.jpg",
      "originalPath": "content/profile-image/IMG_Thur_reserva.JPG",
      "bytes": 3870216
    }
  ],
  "backgrounds": [
    {
      "id": "background-sunset2",
      "kind": "background",
      "title": "sunset2",
      "filename": "sunset2.png",
      "format": "png",
      "src": "/media/backgrounds/sunset2.jpg",
      "originalPath": "content/background-images/sunset2.png",
      "bytes": 743063
    }
  ]
}
