/* Auto-generated by scripts/scan-media.mjs — do not edit */
import type { MediaManifest } from '@/lib/media'

export const mediaManifest: MediaManifest = {
  "generatedAt": "2026-08-18T14:55:08.971Z",
  "tracks": [
    {
      "id": "track-house-base",
      "kind": "track",
      "title": "house base",
      "filename": "house-base.mp3",
      "format": "mp3",
      "src": "/media/tracks/house-base.mp3",
      "originalPath": "public/media/tracks/house-base.mp3",
      "bytes": 1996217,
      "waveformSrc": "/media/waveforms/house-base.json"
    },
    {
      "id": "track-illuminated-path",
      "kind": "track",
      "title": "illuminated path",
      "filename": "illuminated-path.mp3",
      "format": "mp3",
      "src": "/media/tracks/illuminated-path.mp3",
      "originalPath": "public/media/tracks/illuminated-path.mp3",
      "bytes": 2881036,
      "waveformSrc": "/media/waveforms/illuminated-path.json"
    },
    {
      "id": "track-kfx",
      "kind": "track",
      "title": "kfx",
      "filename": "kfx.mp3",
      "format": "mp3",
      "src": "/media/tracks/kfx.mp3",
      "originalPath": "public/media/tracks/kfx.mp3",
      "bytes": 5150137,
      "waveformSrc": "/media/waveforms/kfx.json"
    },
    {
      "id": "track-lucido",
      "kind": "track",
      "title": "lucido",
      "filename": "lucido.mp3",
      "format": "mp3",
      "src": "/media/tracks/lucido.mp3",
      "originalPath": "public/media/tracks/lucido.mp3",
      "bytes": 3964386,
      "waveformSrc": "/media/waveforms/lucido.json"
    },
    {
      "id": "track-piano",
      "kind": "track",
      "title": "piano",
      "filename": "piano.mp3",
      "format": "mp3",
      "src": "/media/tracks/piano.mp3",
      "originalPath": "public/media/tracks/piano.mp3",
      "bytes": 4759345,
      "waveformSrc": "/media/waveforms/piano.json"
    },
    {
      "id": "track-soulful-dreams",
      "kind": "track",
      "title": "soulful dreams",
      "filename": "soulful-dreams.mp3",
      "format": "mp3",
      "src": "/media/tracks/soulful-dreams.mp3",
      "originalPath": "public/media/tracks/soulful-dreams.mp3",
      "bytes": 4079743,
      "waveformSrc": "/media/waveforms/soulful-dreams.json"
    }
  ],
  "sets": [
    {
      "id": "set-thur-mershup-techno-x-prog-house",
      "kind": "set",
      "title": "thur mershup techno x prog house",
      "filename": "thur-mershup-techno-x-prog-house.mp3",
      "format": "mp3",
      "src": "/media/sets/thur-mershup-techno-x-prog-house.mp3",
      "originalPath": "public/media/sets/thur-mershup-techno-x-prog-house.mp3",
      "bytes": 30096870,
      "waveformSrc": "/media/waveforms/thur-mershup-techno-x-prog-house.json"
    },
    {
      "id": "set-thur-mix-rec-2022-02-19",
      "kind": "set",
      "title": "thur mix rec 2022 02 19",
      "filename": "thur-mix-rec-2022-02-19.mp3",
      "format": "mp3",
      "src": "/media/sets/thur-mix-rec-2022-02-19.mp3",
      "originalPath": "public/media/sets/thur-mix-rec-2022-02-19.mp3",
      "bytes": 43868689,
      "waveformSrc": "/media/waveforms/thur-mix-rec-2022-02-19.json"
    },
    {
      "id": "set-thur-tech-house-music-mix01012022",
      "kind": "set",
      "title": "thur tech house music mix01012022",
      "filename": "thur-tech-house-music-mix01012022.mp3",
      "format": "mp3",
      "src": "/media/sets/thur-tech-house-music-mix01012022.mp3",
      "originalPath": "public/media/sets/thur-tech-house-music-mix01012022.mp3",
      "bytes": 29211650,
      "waveformSrc": "/media/waveforms/thur-tech-house-music-mix01012022.json"
    },
    {
      "id": "set-thur2guima-progressive-sunrise-19-03-22",
      "kind": "set",
      "title": "thur2guima progressive sunrise 19 03 22",
      "filename": "thur2guima-progressive-sunrise-19-03-22.mp3",
      "format": "mp3",
      "src": "/media/sets/thur2guima-progressive-sunrise-19-03-22.mp3",
      "originalPath": "public/media/sets/thur2guima-progressive-sunrise-19-03-22.mp3",
      "bytes": 65744253,
      "waveformSrc": "/media/waveforms/thur2guima-progressive-sunrise-19-03-22.json"
    },
    {
      "id": "set-thur2luca-house-music-sunset",
      "kind": "set",
      "title": "thur2luca house music sunset",
      "filename": "thur2luca-house-music-sunset.mp3",
      "format": "mp3",
      "src": "/media/sets/thur2luca-house-music-sunset.mp3",
      "originalPath": "public/media/sets/thur2luca-house-music-sunset.mp3",
      "bytes": 79645927,
      "waveformSrc": "/media/waveforms/thur2luca-house-music-sunset.json"
    }
  ],
  "photos": [
    {
      "id": "photo-boat-img-jul-2023-1",
      "kind": "photo",
      "title": "boat img jul 2023 1",
      "filename": "boat-img-jul-2023-1.jpg",
      "format": "jpg",
      "src": "/media/fotos/boat-img-jul-2023-1.jpg",
      "originalPath": "public/media/fotos/boat-img-jul-2023-1.jpg",
      "bytes": 148552
    },
    {
      "id": "photo-boat-img-jul-2023-2",
      "kind": "photo",
      "title": "boat img jul 2023 2",
      "filename": "boat-img-jul-2023-2.jpg",
      "format": "jpg",
      "src": "/media/fotos/boat-img-jul-2023-2.jpg",
      "originalPath": "public/media/fotos/boat-img-jul-2023-2.jpg",
      "bytes": 143141
    },
    {
      "id": "photo-boat-img-jul-2023-3",
      "kind": "photo",
      "title": "boat img jul 2023 3",
      "filename": "boat-img-jul-2023-3.jpg",
      "format": "jpg",
      "src": "/media/fotos/boat-img-jul-2023-3.jpg",
      "originalPath": "public/media/fotos/boat-img-jul-2023-3.jpg",
      "bytes": 62770
    },
    {
      "id": "photo-img-hand",
      "kind": "photo",
      "title": "img hand",
      "filename": "img-hand.jpg",
      "format": "jpg",
      "src": "/media/fotos/img-hand.jpg",
      "originalPath": "public/media/fotos/img-hand.jpg",
      "bytes": 67106
    },
    {
      "id": "photo-img-thur",
      "kind": "photo",
      "title": "img thur",
      "filename": "img-thur.jpg",
      "format": "jpg",
      "src": "/media/fotos/img-thur.jpg",
      "originalPath": "public/media/fotos/img-thur.jpg",
      "bytes": 179748
    }
  ],
  "profile": [
    {
      "id": "profile-img-thur-reserva",
      "kind": "profile",
      "title": "img thur reserva",
      "filename": "img-thur-reserva.jpg",
      "format": "jpg",
      "src": "/media/profile/img-thur-reserva.jpg",
      "originalPath": "public/media/profile/img-thur-reserva.jpg",
      "bytes": 306898
    }
  ],
  "backgrounds": []
}
